update jotai to v1.6.0  and correct example to make it work fine
pmndrs/jotai pull request #1047
Opened 2022-03-06 19:57 UTC by tsingson

update example to make its work correct.

2022-03-07 00:15 UTC, dai-shi requested changes
Thanks for working on this. A quick first review.

2022-03-07 00:15 UTC, dai-shi commented on examples/hacker_news/src/App.tsx
> +import { atomWithQuery } from 'jotai/query'
We don't want to change this example with RQ. If you need such a example, please create a new one.

2022-03-07 00:15 UTC, dai-shi commented
> to make its work correct.

what was the incorrect example, previously?

2022-06-03 01:33 UTC, TwistedMinda commented
@tsingson Hey tsingson, do you think you will be able to complete this? 

I can take care of updating to last version & fixing the problem, but do you remember what was not working in the first place?

The [Example CodeSandBox](https://codesandbox.io/s/github/pmndrs/jotai/tree/main/examples/hacker_news?file=/src/App.tsx) seems to be working just fine

2022-06-03 17:29 UTC, TwistedMinda commented
@dai-shi I guess we can close it and we'll rework examples if there is a bug found or we make a major update. Correct me if I'm wrong.
Most important is that the example is working fine.

OP can still comment here if he has an issue

2022-06-03 17:29 UTC, closed without merging