docs: Minor language change for more accurate reading
pmndrs/jotai pull request #1083
Opened 2022-04-04 17:12 UTC by pietgit

Hi, I added a small improvement to the docs to make the below sentence a little more accurate (Objects and Arrays aren't primitive types in JS). 

from

"First create a primitive atom.
An atom represents a piece of state. All you need is to specify an initial value, which can be a primitive value like a string, number, object or array. You can create as many primitive atoms as you like."

to

"First create a primitive atom.
An atom represents a piece of state. All you need is to specify an initial
value, which can be a **primitive value like a string or number, or an object or
array.** You can create as many primitive atoms as you like."

More info: I'm new to Jotai, and are going to use it for a project upgrade, and found myself wondering about the usage of the term 'primitive' here.

2022-04-05 00:41 UTC, AjaxSolutions commented
How do you like this description?

"A piece of state in Jotai is represented by an atom. An atom accepts an initial value, be it a primitive type like a number, string, or more complex structures like arrays and objects."

https://dmitripavlutin.com/react-jotai-state-management/

2022-04-05 08:39 UTC, pietgit commented
> 

Yes, that's perfect. I've added the following into a new commit:

"A piece of state in Jotai is represented by an atom. All you need is to specify
an initial value, be it a primitive type like a number, string, or more complex
structures like arrays and objects. You can create as many primitive atoms as you like."

2022-04-05 19:02 UTC, sandren commented
@pietgit  Thank you for making the language more accurate. 🙂

Though perhaps it would be even easier to understand our meaning of the term 'primitive atom' if we remove the reference to 'primitive types' altogether since it isn't necessary for the explanation of atoms?

2022-04-05 19:41 UTC, AjaxSolutions commented
@sandren Jotai is defined as "Primitive and flexible state management for React"

What does primitive mean?  Does it mean that it's low-level?

https://jotai.org/

2022-04-05 23:41 UTC, dai-shi commented
> @sandren Jotai is defined as "Primitive and flexible state management for React"
> 
> What does primitive mean? Does it mean that it's low-level?

It's me who noted "primitive and flexible". I wanted to emphasize it's considered as building blocks.
atom+useAtom is a replacement for useState(+useContext). I would say useState is low-level as well as atom+useAtom.
jotai/utils and other jotai/* are all developed on jotai core public api. so, I think it's very flexible.

2022-04-15 12:22 UTC, dai-shi requested changes
Would love to see this change. https://github.com/pmndrs/jotai/pull/1083#issuecomment-1089199467

2022-05-18 23:57 UTC, dai-shi commented
@pietgit are you still around?

2022-06-02 18:38 UTC, TwistedMinda commented
@pietgit If u're not available I can take care of this, we can close this PR and i'll create one from this. Seems like a small change that we can do fast, no need to let it stale

2022-06-03 02:21 UTC, closed without merging