feat(utils) - Optionally rehydrate with force hydrate
pmndrs/jotai pull request #1990
Opened 2023-06-14 15:19 UTC by SariSabouh

## Related Issues or Discussions

The useHydrateAtom discussion has been live since August of 2021 in https://github.com/pmndrs/jotai/discussions/669.

## Summary

We found a use case within our project that required a rehydration after a specific event. We had to manually rely on conditional useEffect actions to manually update the store rather than hydrating back from a fully reset SSR page. After review, a forceHydration option meets that requirement and a lot of the cases mentioned within that option discussion.

## Check List

- [X] `yarn run prettier` for formatting code and docs

2023-06-15 00:03 UTC, dai-shi requested changes
Thanks for your suggestion. Added some comments.

2023-06-15 00:03 UTC, dai-shi commented on src/react/utils/useHydrateAtoms.ts
> +
Can it be as simple as this?
```suggestion
    if (!hydratedSet.has(atom) || options?.dangerouslyForceHydrate) {
```

2023-06-15 13:42 UTC, SariSabouh commented on src/react/utils/useHydrateAtoms.ts
> +  forceHydrate?: boolean
That's a great catch! Will definitely update 👍

2023-06-15 13:47 UTC, SariSabouh commented
Added all requested changes @dai-shi

2023-06-15 14:41 UTC, dai-shi commented on tests/react/utils/useHydrateAtoms.test.tsx
> +it.only('passing dangerouslyForceHydrate to useHydrateAtoms will re-hydrated atoms', async () => {
```suggestion
it('passing dangerouslyForceHydrate to useHydrateAtoms will re-hydrated atoms', async () => {
```

2023-06-15 14:53 UTC, SariSabouh commented on tests/react/utils/useHydrateAtoms.test.tsx
> +it('passing dangerouslyForceHydrate to useHydrateAtoms will re-hydrated atoms', async () => {
Great catch, forgot to remove while testing :)

2023-06-15 23:18 UTC, dai-shi commented
On second thought, we could do and suggest to use store api for such use cases.
```js
const Component = () => {
  const store = useStore()
  store.set(countAtom, countValue)
  // ...
}
```

What do you think?

2023-06-16 13:11 UTC, SariSabouh commented
> On second thought, we could do and suggest to use store api for such use cases.
> 
> ```js
> const Component = () => {
>   const store = useStore()
>   store.set(countAtom, countValue)
>   // ...
> }
> ```
> 
> What do you think?

Basically disregard the forceHydrate and suggest using the store API? If yes, that could technically fully replace the `useHydrateAtom` though and may cause many re-renders in some cases, especially if its an object compare.

2023-06-16 13:24 UTC, dai-shi commented
Basically disregard force hydrate, but store api wouldn't fully replace useHydreteAtoms which ensures only setting values if unset.

> may cause many re-renders in some cases

I'm not sure if I get those cases.

2023-06-16 13:32 UTC, SariSabouh commented
> Basically disregard force hydrate, but store api wouldn't fully replace useHydreteAtoms which ensures only setting values if unset.
> 
> > may cause many re-renders in some cases
> 
> I'm not sure if I get those cases.

I can try to re-produce it again but I remember going for the `forceHydrate` because useStore was was causing a re-render. Is there a reason you're opposed to going with some sort of re-hydrate method? I was thinking we can integrate atomsWithReset somehow instead.

2023-06-16 13:40 UTC, dai-shi commented
The reason to be against `dangerouslyForceHydrate` (the name is actually good to warn the usage) is that it bypasses the hydration check, and the result is just equal to `store.set(...)`. It means we provide two ways for the same capability which we carefully avoid in Jotai API design.

2023-06-16 13:48 UTC, SariSabouh commented
So you are suggesting that we do something like this:

```typescript
export const Component = ({
  componentPreferences,
}: ComponentPageProps) => {
  useHydrateAtoms([[componentPreferencesAtom, componentPreferences]])
  const store = useStore()
  componentPreferencesValue.reset &&
    store.set(componentPreferencesAtom, componentPreferences)
```

2023-06-16 13:56 UTC, dai-shi commented
I'm not sure if I understand the purpose of "reset", but my suggestion was if you use `store.set()` you don't use useHydrateAtoms.

Ah, I see you want to force hydrate if reset is true, and otherwise, only hydrate initially.
Hm, that use case supports this PR's change.
My suggestion to go against this PR would require `store.has()` method which doesn't exist.

2023-06-16 14:02 UTC, SariSabouh commented
I'm open to ideas. The issue is that we hydrate a page with data that is needed until a certain action completion. Once this action is completed, we want to fully reset that atom and get new data from SSR on next time this page loads.

2023-06-16 14:12 UTC, dai-shi commented
I feel like merging this PR as the code is clean and it has `dangerously` prefix to warn the usage.
After all, it is in `jotai/utils` which is a little less strict about API design.

> we want to fully reset that atom and get new data from SSR on next time this page loads.

I'm curious about your case. When you get new data from SSR on next time, how would the store be kept in memory (assumed so because you want to fully reset) ?

2023-06-16 14:39 UTC, dai-shi commented
> and completes a certain action

Hmm? If this is a user action, we should update atoms at the same time. Updating atoms in render is something we should really avoid. It's not just bad practice, but theoretically delayed.

2023-06-16 14:43 UTC, SariSabouh commented
So once the user completes the action it takes him out of the page. And they won't get the newest set of data until they reach that page.

Like once you complete checkout, you are taken out of checkout and your checkout data is reset. However, once you come back from checkout, you need the newest set of data from the server to be hydrated again. Client side won't know the data until they reach checkout, which is SSR.

2023-06-16 14:55 UTC, dai-shi commented
I'm not exactly sure how the second SSR&hydration work, but it sounds like you can only get the new data from props. In that case, the render time updating wouldn't be avoidable. Can't be helped because you don't have control, right? Sounds fair enough, because we usually suggest useEffect for sync with props, but that's far from ideal.

2023-06-16 15:04 UTC, dai-shi commented
I think there should be a better way, probably atoms-in-atom or jotai-molecules, and we want to educate such ones for common use cases.

This PR change helps as an escape hatch for edge cases, so I want to merge, but we shouldn't teach people to use it for common cases.

2023-06-16 15:05 UTC, dai-shi approved these changes
Thanks for the discussion. It was convincing. I will merge it later.

2023-06-16 15:11 UTC, SariSabouh commented
> I think there should be a better way, probably atoms-in-atom or jotai-molecules, and we want to educate such ones for common use cases.
> 
> This PR change helps as an escape hatch for edge cases, so I want to merge, but we shouldn't teach people to use it for common cases.

Haven't messed with jotai-molecules yet, but definitely will give them a shot!

2023-06-18 23:03 UTC, merged