improve useAtom error message
pmndrs/jotai pull request #202
Opened 2020-11-19 20:21 UTC by Aslemammad

I was playing with codesandbox, then jotai showed me that error, but I had a provider, then I realized that I didn't put the scope. Maybe helpful for the folks.

2020-11-19 23:03 UTC, dai-shi requested changes
Thanks for the suggestion! can you change a bit?

2020-11-19 23:03 UTC, dai-shi commented on src/core/useAtom.ts
>  function assertContextValue<T extends object>(x: T | null): asserts x is T {
```suggestion
function assertContextValue<T extends object>(x: T | null, scope?: unknown): asserts x is T {
```

Let's show the note about the scope only if scope is specified. I suppose, the majority of users don't use scopes.

2020-11-19 23:14 UTC, dominictwlee commented on src/core/useAtom.ts
> +      'Please use <Provider> or if you have scoped atoms, use <Provder scope={yourAtomScope}>'
```suggestion
      'Please use <Provider> or if you have scoped atoms, use <Provider scope={yourAtomScope}>'
```

2020-11-20 12:46 UTC, Aslemammad commented
I think it's ready now.

2020-11-20 16:22 UTC, dai-shi approved these changes
LGTM

2020-11-20 16:23 UTC, merged