fix(vanilla): should mount once with atom creator atom
pmndrs/jotai pull request #2319
Opened 2024-01-01 18:16 UTC by nogaten

## Related Issues or Discussions

Fixes #2314

## Summary
I'm sorry about the previous PR.
Changed evaluation of canUnmountAtom in mountDependencies function after mountAtom.

## Check List

- [ ] `yarn run prettier` for formatting code and docs

2024-01-02 21:08 UTC, himself65 reviewed
Can you add the test case?

2024-01-08 02:31 UTC, dai-shi requested changes
Please add the test case: https://github.com/pmndrs/jotai/issues/2314#issuecomment-1873058709

2024-01-08 14:18 UTC, nogaten commented
Of course @himself65, @dai-shi. Added test.

2024-01-08 18:36 UTC, himself65 reviewed
lgtm

2024-01-08 22:43 UTC, himself65 approved these changes

2024-01-09 01:46 UTC, himself65 commented
some type error might need to fix

2024-01-15 11:00 UTC, dai-shi requested changes
@nogaten can you fix CI errors?

2024-01-15 11:00 UTC, dai-shi commented on tests/vanilla/store.test.tsx
> +  countAtom.onMount = vi.fn((setAtom) => {
Please explicitly type `setAtom` for older TS tests.

2024-01-16 01:58 UTC, dai-shi commented on tests/vanilla/store.test.tsx
> +  countAtom.onMount = vi.fn((setAtom) => {
```suggestion
  countAtom.onMount = vi.fn((setAtom: (v: number) => void) => {
```

2024-01-16 02:03 UTC, dai-shi approved these changes

2024-01-16 02:05 UTC, merged