add configuration for vite react-wsc
pmndrs/jotai pull request #2320
Opened 2024-01-02 02:41 UTC by SpringHgui

## Related Issues or Discussions

Fixes #

## Summary

## Check List

- [ ] `yarn run prettier` for formatting code and docs

2024-01-02 21:08 UTC, himself65 approved these changes

2024-01-04 07:08 UTC, hyoban commented on website/src/pages/index.js
> +npm install --save-dev @swc-jotai/react-refresh
```suggestion
npm install --save-dev @swc-jotai/react-refresh @swc-jotai/debug-label
```

2024-01-05 03:42 UTC, sandren requested changes
Thanks for looking into this.

Can we reduce the plugins to only `@swc-jotai/react-refresh` to match the instructions for the other environments? Thanks! 🙂 

Also we'll want to confirm that inline atom declarations are working since there has been some trouble with Next.js (SWC).

2024-01-05 09:34 UTC, SpringHgui commented
I don't quite understand what you mean, what else needs to be done @sandren

2024-01-23 05:43 UTC, sandren approved these changes

2024-01-23 05:53 UTC, merged