fix: add parentheses to catch
pmndrs/jotai pull request #2419
Opened 2024-02-25 15:49 UTC by amirhhashemi

## Related Issues or Discussions

https://github.com/pmndrs/jotai/issues/48

## Summary

The ability to omit the parentheses in front of `catch` was introduced in ES2019. It causes a syntax error in the browsers that don't support it like Chrome 65. I'm not sure what browsers you officially support, but if you want to to support Chrome 65 and older, please merge this. It's so hard to debug.

## Check List

- [ ] `yarn run prettier` for formatting code and docs

2024-02-25 17:56 UTC, vincentfretin commented
Probably not related to this, I coincidentally just got a sentry error of a user with an iPad with iOS 12.5.7 so probably one of the 10 years old devices like iPad Air, mini 2 or mini 3 that can't update to iOS 13.
I asked gpt-4:
The optional catch binding feature in JavaScript, which allows omitting the parentheses and the error parameter in a catch block when the error is not used, was introduced in ECMAScript 2019 (ES10). Safari started supporting this feature starting from Safari 13.

2024-02-25 23:21 UTC, dai-shi approved these changes
Thanks!
Yeah, I generally avoid omitting `()` to catch, but forgot in these places.
I wonder if there's an eslint rule to prohibit it.

2024-02-26 05:06 UTC, dai-shi commented
@amirhhashemi 
That's a good insight actually.
We should probably change the target.
This seems to work. Can you try it, and change this PR?

```diff
diff --git a/rollup.config.js b/rollup.config.js
index 66c8f0e..afd185f 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -33,10 +33,11 @@ function getBabelOptions(targets) {
   }
 }
 
-function getEsbuild(target, env = 'development') {
+function getEsbuild(env = 'development') {
   return esbuild({
     minify: env === 'production',
-    target,
+    target: 'es2018',
+    supported: { 'import-meta': true },
     tsconfig: path.resolve('./tsconfig.json'),
   })
 }
@@ -78,7 +79,7 @@ function createESMConfig(input, output, clientOnly) {
         delimiters: ['\\b', '\\b(?!(\\.|/))'],
         preventAssignment: true,
       }),
-      getEsbuild('node12'),
+      getEsbuild(),
       banner2(() => clientOnly && cscComment),
     ],
   }
@@ -157,7 +158,7 @@ function createSystemConfig(input, output, env, clientOnly) {
         delimiters: ['\\b', '\\b(?!(\\.|/))'],
         preventAssignment: true,
       }),
-      getEsbuild('node12', env),
+      getEsbuild(env),
       banner2(() => clientOnly && cscComment),
     ],
   }
```

2024-02-26 05:07 UTC, dai-shi requested changes
https://github.com/pmndrs/jotai/pull/2419#issuecomment-1963327016

2024-02-26 05:50 UTC, amirhhashemi commented
Yeah I think it works.

Before:
```sh
$ yarn run build
$ grep -o 'catch{' ./dist/**/*.js
./dist/system/vanilla/utils.production.js:catch{
./dist/system/vanilla/utils.production.js:catch{
./dist/system/vanilla/utils.production.js:catch{
```
After:
```sh
$ yarn run build
$ grep -o 'catch{' ./dist/**/*.js
# There is no 'catch{` in the build output
```

2024-02-26 05:55 UTC, dai-shi commented
btw you want to grep `catch {`.

2024-02-26 05:56 UTC, dai-shi approved these changes
Thanks for the change.
(We should probably do the same for Zustand and Valtio.)

2024-02-26 05:58 UTC, amirhhashemi commented
> btw you want to grep `catch {`.

Isn't the build output minified?

2024-02-26 06:01 UTC, dai-shi commented
No, for esm and cjs builds, we don't minify.

2024-02-26 06:07 UTC, amirhhashemi commented
I tried `catch {` and the result is the same:
Before:
```sh
$ grep -o 'catch {' ./dist/**/*.js
./dist/system/vanilla/utils.development.js:catch {
./dist/system/vanilla/utils.development.js:catch {
```
After:
```sh
$ yarn run build
$ grep -o 'catch {' ./dist/**/*.js
# There is no 'catch {` in the build output
```

2024-02-26 06:18 UTC, dai-shi commented
Interesting. I get this:
```
$ ag 'catch {' dist|cat        
dist/esm/vanilla/utils.mjs:355:          } catch {
dist/esm/vanilla/utils.mjs:391:          } catch {
dist/system/vanilla/utils.development.js:379:                } catch {
dist/system/vanilla/utils.development.js:415:                } catch {
```

2024-02-26 06:28 UTC, amirhhashemi commented
Wired. I tried it again and it seems to be working. Did you run `yarn run build` before grep?

2024-02-26 07:48 UTC, dai-shi commented
This isn't super important, but just curious.

I run `yarn build` again and here's the result:
```sh
$ grep 'catch {' dist/esm/vanilla/utils.mjs 
          } catch {
          } catch {
```

2024-02-26 09:42 UTC, dai-shi commented
> (We should probably do the same for Zustand and Valtio.)

https://github.com/pmndrs/zustand/pull/2361
https://github.com/pmndrs/valtio/pull/863

2024-02-28 03:00 UTC, merged