add a optimization test to avoid extra rerender
pmndrs/jotai pull request #2558
Opened 2024-05-17 03:48 UTC by hjiog

## Related Issues or Discussions

Fixes #2530 

## Summary
add a optimization test to avoid extra rerender.

## Check List

- [x] `pnpm run prettier` for formatting code and docs

2024-05-17 06:00 UTC, dai-shi commented on tests/react/optimization.test.tsx
> +it.skip('no extra rerenders after mounted (#2530)', async () => {
```suggestion
it('no extra rerenders after mounted (#2558)', async () => {
```

2024-05-17 06:01 UTC, dai-shi commented
We should probably add another test to ensure that `rerender()` in useEffect is required, before tackling this.

2024-05-28 12:08 UTC, dai-shi requested changes
> We should probably add another test to ensure that rerender() in useEffect is required, before tackling this.

Please create a test for `rerender()` first before tackling this. Otherwise, you don't know why we need it. It thinks it's reasonable to create a separate PR.

> Another point is that this optimization should be handled with React binding. There's nothing wrong in store implementation.

Please do not modify store implementation.

2024-05-28 12:34 UTC, hjiog commented
If I have uderstood correctly, `rerender()` is to ensure that all the components have executed the subscription logic, so that there will be no problem when the onMounted method is called. But I don't know how to create a test for `rerender()`. Yea,  this optimization can be handled with React binding, but what if we do it better? This PR can be used as a reference idea. If someone is interested, welcome to improve it.

2024-05-28 13:13 UTC, dai-shi commented
Yeah, let's leave it for now. Here's some comments for the future.

`rerender()` exists because `useEffect` is async.
I think `useLayoutEffect` instead might be a fix (but I haven't confirmed),
but it will probably be a major bump with React 19 requirement (or maybe 18).

If we were to optimize it in Jotai v2, it must be within the hook.
It should be technically possible with something like `use-sync-external-store` shim.

2024-08-18 00:51 UTC, dai-shi commented
Closing this for now.

If anyone is interested, feel free to develop a third-party library (that provides its own `useAtomValue`) and do some experiments.
I can invite someone to https://github.com/jotaijs if they work on it.

2024-08-18 00:51 UTC, closed without merging

2025-03-20 07:35 UTC, suguanYang commented
> Yeah, let's leave it for now. Here's some comments for the future.
> 
> `rerender()` exists because `useEffect` is async. I think `useLayoutEffect` instead might be a fix (but I haven't confirmed), but it will probably be a major bump with React 19 requirement (or maybe 18).
> 
> If we were to optimize it in Jotai v2, it must be within the hook. It should be technically possible with something like `use-sync-external-store` shim.

Sorry for bring this up, maybe we could write something like this?
```javascript

const useStoreSubSync = (atom) => {
  const store = useStore();
  const listenerRef = useRef(null)
  {
    listenerRef.current = listenerRef.current || store.sub(atom, () => {
      // ...
      rerender()
    })
  }

  useEffect(() => {
    return listenerRef.current
  }, [])
}
```

2025-03-20 09:58 UTC, dai-shi commented
Unfortunately, useEffect doesn't fire in some cases.

2025-03-20 10:31 UTC, suguanYang commented
I did't get it. we already rely on useEffect, right?

2025-03-20 11:07 UTC, dai-shi commented
What's guaranteed is if useEffect runs once, the cleanup runs once.
You shouldn't make side effects in the render function. There should be lots of discussions and articles about it.