feat: add hook for atom mount and unmount
pmndrs/jotai pull request #2895
Opened 2024-12-30 07:19 UTC by dmaskasky

## Summary
Adds a hook to atomState that is called in-place immediately after atom mount changes.

## Check List

- [x] `pnpm run prettier` for formatting code and docs

2024-12-30 23:55 UTC, dai-shi commented on src/vanilla/store.ts
> +          let originalMounted = atomState.h
```suggestion
          const originalMounted = atomState.h
```

2024-12-30 23:58 UTC, dai-shi reviewed
Looks good to me. Thanks for the suggestion. This is much cleaner.

I'll merge this when we are ready to release another patch.

2024-12-30 23:59 UTC, dai-shi commented
/ecosystem-ci run

2025-01-02 10:36 UTC, dai-shi commented on src/vanilla/store.ts
> +  h?: () => void
If you want to change this with another character, we can reconsider.

2025-01-02 14:49 UTC, dmaskasky commented on src/vanilla/store.ts
> +  h?: () => void
How about
```ts
h?: (action: 'm' | 'u') => void
```

2025-01-02 23:06 UTC, dai-shi commented on src/vanilla/store.ts
> +  h?: () => void
`'m' | 'u'` doesn't look too bad even though it increases the bundle size. I'm hesitant to expose batch here, and looking for an alternative.

2025-01-03 00:48 UTC, dai-shi requested changes

2025-01-03 00:48 UTC, dai-shi commented on src/vanilla/store.ts
> +  u?: () => void
I'd like to make a patch release with only dev store improvement. So, let's remove this in this PR.
```suggestion
```

2025-01-03 00:48 UTC, dai-shi commented on src/vanilla/store.ts
> +  h?: () => void
We may change `'h'` in the future, but as this is considered internal, it's fine.

2025-01-03 00:48 UTC, dai-shi commented on src/vanilla/store.ts
> +    atomState.u?.()
```suggestion
```

2025-01-03 00:55 UTC, dai-shi approved these changes
Much cleaner without Proxy hack.

2025-01-03 01:08 UTC, merged

2025-01-03 04:57 UTC, dmaskasky commented on src/vanilla/store.ts
> +  h?: () => void
> I'm hesitant to expose batch here, and looking for an alternative.

Its pretty central to syncBatch scheduling.

2025-01-03 07:09 UTC, dai-shi commented on src/vanilla/store.ts
> +  h?: () => void
I'm working on it, and not sure if it's successful, but I feel like reverting this PR... Will see.

2025-01-03 15:55 UTC, dai-shi commented on src/vanilla/store.ts
> +  h?: () => void
> Will see.

It failed.